from pathlib import Path

import core.dry_run_execution_contract as dry_run_contract
import core.kill_switch_rollback_contract as kill_switch_contract
import core.runtime_governance_contract as governance_contract
import core.runtime_state_contract as state_contract
from core.runtime_activation_gate import (
    RUNTIME_ACTIVATION_ENABLED,
    RUNTIME_API_ENABLED,
    RUNTIME_BROWSER_ENABLED,
    RUNTIME_CONTEXT_INJECTION_ENABLED,
    RUNTIME_ENV_ACCESS_ENABLED,
    RUNTIME_EXECUTION_ENABLED,
    RUNTIME_FILESYSTEM_ENABLED,
    RUNTIME_HERMES_ENABLED,
    RUNTIME_HOME_ASSISTANT_ENABLED,
    RUNTIME_MEMORY_PERSISTENCE_ENABLED,
    RUNTIME_MODEL_INVOCATION_ENABLED,
    RUNTIME_N8N_ENABLED,
    RUNTIME_NETWORK_ENABLED,
    RUNTIME_OUTPUT_DELIVERY_ENABLED,
    RUNTIME_QUEUE_ENABLED,
    RUNTIME_RUNNER_ENABLED,
    RUNTIME_SCHEDULER_ENABLED,
    RUNTIME_SECRET_ACCESS_ENABLED,
    RUNTIME_STORES_ENABLED,
    RUNTIME_TOOL_EXECUTION_ENABLED,
    RUNTIME_UI_TARS_ENABLED,
    RUNTIME_WORKER_ENABLED,
    RUNTIME_WRITES_ENABLED,
)


ROOT = Path(__file__).resolve().parents[1]
DOC = ROOT / "docs" / "OBSERVABILITY_CONTRACT_AUDIT.md"


def _text() -> str:
    assert DOC.exists()
    return DOC.read_text(encoding="utf-8")


def test_observability_contract_audit_status_and_next_step():
    text = _text()
    for phrase in [
        "Observability Contract Audit",
        "OBSERVABILITY_CONTRACT_AUDIT_COMPLETED",
        "OBSERVABILITY_CONTRACT_BASELINE_VERIFIED",
        "ready_for_observability_contract",
        "PROMPT 3.47 — Contrato de Observability no-operativo",
    ]:
        assert phrase in text


def test_observability_contract_definition_is_pre_contract_only():
    text = _text()
    for phrase in [
        "Observability Contract es la futura capa no-operativa",
        "Observability Contract no es observability runtime",
        "Observability Contract no escribe logs",
        "Observability Contract no crea event bus",
        "Observability Contract no crea telemetry",
        "Observability Contract no crea metrics collector",
        "Observability Contract no crea tracing runtime",
        "Observability Contract no crea dashboard",
        "Observability Contract no crea audit trail operativo",
        "Observability Contract no muta stores",
        "Observability Contract no ejecuta runtime",
        "Observability Contract no invoca tools",
        "Observability Contract no invoca modelos",
        "Observability Contract no inyecta contexto",
        "Observability Contract no entrega outputs",
        "solo auditoria pre-contract",
    ]:
        assert phrase in text


def test_audited_sources_are_complete():
    text = _text()
    for phrase in [
        "Observability / Audit Trail Post-Security Audit",
        "Runtime Governance Contract",
        "Runtime Governance Contract Full E2E",
        "Runtime State Contract",
        "Runtime State Contract Full E2E",
        "Runtime Activation Gate",
        "Runtime Foundation Plan",
        "Dry-run Execution Contract",
        "Dry-run Execution Contract Full E2E",
        "Execution Intent Contract",
        "Execution Attempt ID audit",
        "Execution Attempt schema",
        "Execution Attempt State Machine",
        "Attempt Factory contract",
        "Attempt Store write-safe contract",
        "Lifecycle Writer contract",
        "Execution Result contract",
        "Execution Result Projection",
        "Execution History View",
        "Internal Backend Read Model",
        "Kill Switch / Rollback Contract",
        "Human Approval Gate Plan",
        "Security Layer Final Checkpoint",
        "Agent Permission Contract",
        "Secrets Policy",
        "Prompt Injection Defense",
        "Sandbox Boundary",
        "Tool Boundary",
        "Model Invocation Boundary",
        "Context Boundary",
        "Output Boundary",
        "core/observability.py preexisting/no-mutant status",
        "archivo/modulo/documento asociado",
        "preexisting-no-mutant",
    ]:
        assert phrase in text


def test_conceptual_events_and_rules_are_listed():
    text = _text()
    for phrase in [
        "observability_event_contract_initialized",
        "observability_event_governance_evaluated",
        "observability_event_runtime_state_snapshot_created",
        "observability_event_runtime_state_transition_simulated",
        "observability_event_security_blocked",
        "observability_event_policy_blocked",
        "observability_event_dry_run_required",
        "observability_event_human_approval_required",
        "observability_event_audit_trail_required",
        "observability_event_kill_switch_required",
        "observability_event_rollback_required",
        "observability_event_attempt_created_simulated",
        "observability_event_lifecycle_transition_simulated",
        "observability_event_result_projected",
        "observability_event_output_boundary_checked",
        "observability_event_metadata_rejected",
        "observability_event_secret_redacted",
        "observability_event_integration_blocked",
        "observability_event_obliteratus_excluded",
        "observability_event_archived_simulated",
        "No se escriben en logs reales",
        "No se publican en event bus",
        "No generan telemetry",
        "No generan metrics",
        "No generan tracing real",
        "No generan dashboard",
        "No escriben stores",
        "No activan runtime",
        "No habilitan tools/modelos/context/output",
        "No habilitan integraciones",
    ]:
        assert phrase in text


def test_forbidden_events_are_listed():
    text = _text()
    for phrase in [
        "observability_event_runtime_started",
        "observability_event_runtime_executed",
        "observability_event_runner_started",
        "observability_event_scheduler_started",
        "observability_event_worker_started",
        "observability_event_queue_started",
        "observability_event_executor_started",
        "observability_event_tool_executed",
        "observability_event_model_invoked",
        "observability_event_context_injected",
        "observability_event_output_delivered",
        "observability_event_output_published",
        "observability_event_write_performed",
        "observability_event_store_mutated",
        "observability_event_memory_persisted",
        "observability_event_network_called",
        "observability_event_api_called",
        "observability_event_browser_opened",
        "observability_event_filesystem_read",
        "observability_event_filesystem_written",
        "observability_event_env_read",
        "observability_event_secret_read",
        "observability_event_ui_controlled",
        "observability_event_device_controlled",
        "observability_event_integration_executed",
        "observability_event_market_catalog_runtime_started",
        "observability_event_business_composition_runtime_started",
        "eventos explicitamente prohibidos",
    ]:
        assert phrase in text


def test_observability_matrix_metadata_forbidden_data_gaps_and_risks():
    text = _text()
    for phrase in [
        "Event identity",
        "Event type",
        "Event source",
        "Event scope",
        "Event correlation",
        "Event causality",
        "Event timestamp policy",
        "Event actor/requester reference",
        "Event governance reference",
        "Event runtime state reference",
        "Event dry-run reference",
        "Event attempt reference",
        "Event lifecycle reference",
        "Event result reference",
        "Event projection/read model reference",
        "Event approval reference",
        "Event kill switch reference",
        "Event rollback reference",
        "Event security baseline reference",
        "Event policy check reference",
        "Event metadata sanitization",
        "Event secret redaction",
        "Event raw payload exclusion",
        "Event raw output exclusion",
        "Event side-effect guarantee",
        "Event serialization",
        "Event determinism",
        "Event archival simulation",
        "Event integration boundary",
        "Event OBLITERATUS exclusion",
        "cobertura actual",
        "requisito minimo futuro",
    ]:
        assert phrase in text
    for phrase in [
        "observability_event_id",
        "correlation_id",
        "causation_id optional",
        "event_type",
        "event_source",
        "event_scope",
        "actor_ref optional",
        "runtime_governance_ref optional",
        "runtime_state_ref optional",
        "runtime_gate_ref optional",
        "security_baseline_ref",
        "policy_check_ref optional",
        "dry_run_ref optional",
        "attempt_id optional",
        "lifecycle_ref optional",
        "result_ref optional",
        "projection_ref optional",
        "human_approval_ref optional",
        "kill_switch_ref optional",
        "rollback_ref optional",
        "event_reason",
        "event_risk_level",
        "event_created_at_controlled optional",
        "metadata_sanitized",
    ]:
        assert phrase in text
    for phrase in [
        "secret",
        "secrets",
        "api_key",
        "apikey",
        "token",
        "access_token",
        "refresh_token",
        "password",
        "passwd",
        "credential",
        "credentials",
        "private_key",
        "raw_payload",
        "payload",
        "raw_output",
        "output",
        "file_content",
        "env",
        "environment",
        "cookie",
        "authorization",
        "bearer",
        "raw_prompt",
        "prompt",
        "raw_completion",
        "completion",
        "model_response",
        "tool_response",
        "external_response",
        "browser_content",
        "filesystem_content",
        "personal_data_unsanitized",
    ]:
        assert phrase in text
    for phrase in [
        "No existe Observability Contract",
        "No existe Observability Contract E2E",
        "No existe observability event schema no-operativo",
        "No existe observability snapshot contract",
        "No existe observability metadata sanitizer propio",
        "No existe correlation contract",
        "No existe causation contract",
        "No existe audit reference contract",
        "No existe side-effect observability contract",
        "No existe immutable audit log contract no-operativo",
        "No existe redaction contract",
        "No existe observability integration boundary",
        "No existe observability archival simulation contract",
        "No existe observability read model projection contract",
        "Estos gaps son esperados",
        "No deben resolverse en este prompt",
    ]:
        assert phrase in text
    for phrase in [
        "Confundir Observability Contract con observability runtime",
        "Crear logger operativo antes del contrato",
        "Crear event bus real antes del contrato",
        "Escribir logs reales desde un contrato",
        "Registrar secretos en eventos",
        "Registrar raw payloads en eventos",
        "Registrar raw outputs en eventos",
        "Registrar prompts crudos o respuestas crudas de modelos",
        "Usar observability como bypass de Output Boundary",
        "Usar observability como bypass de Secrets Policy",
        "Usar observability como bypass de Runtime Governance",
        "Usar observability como prueba de ejecucion real",
        "Permitir telemetry/tracing/dashboard operativo",
        "Crear correlation ledger operativo antes de contrato",
        "Crear side-effect ledger operativo antes de runtime gobernado",
        "Activar integraciones via eventos",
        "Incorporar OBLITERATUS como observability source por accidente",
        "mitigacion existente",
        "mitigacion faltante",
    ]:
        assert phrase in text


def test_recommendation_for_next_contract_is_present():
    text = _text()
    for phrase in [
        "PROMPT 3.47 — Contrato de Observability no-operativo",
        "La auditoria confirma que existe base suficiente",
        "ser contract-only",
        "ser no-operational",
        "depender de Runtime Governance",
        "depender de Runtime State",
        "depender de Security Layer",
        "definir eventos conceptuales",
        "bloquear eventos reales",
        "validar metadata sanitizada",
        "rechazar secrets/raw payloads/raw outputs/prompts crudos/model responses crudos",
        "producir snapshots observables serializables",
        "producir referencias de correlacion conceptuales",
        "ser determinista",
        "no tener side effects",
        "no escribir logs",
        "no crear event bus",
    ]:
        assert phrase in text


def test_forbidden_modules_and_explicit_blockers_are_listed():
    text = _text()
    for phrase in [
        "core/observability_event.py",
        "core/observability_event_schema.py",
        "core/observability_snapshot.py",
        "core/observability_store.py",
        "core/observability_writer.py",
        "core/observability_reader.py",
        "core/observability_logger.py",
        "core/audit_trail.py",
        "core/audit_logger.py",
        "core/event_log.py",
        "core/event_bus.py",
        "core/telemetry.py",
        "core/metrics_collector.py",
        "core/tracing.py",
        "core/dashboard.py",
        "core/correlation_ledger.py",
        "core/immutable_audit_log.py",
        "core/side_effect_ledger.py",
        "core/redaction_engine.py",
        "core/runtime_state.py",
        "core/runtime_state_machine.py",
        "core/runtime_state_validator.py",
        "core/runtime_state_store.py",
        "core/runtime_state_writer.py",
        "core/runtime_state_reader.py",
        "core/runtime_state_event.py",
        "core/runtime_state_event_bus.py",
        "core/runtime_governance.py",
        "core/runtime_controller.py",
        "core/runtime_manager.py",
        "core/runtime_runner.py",
        "core/runtime_scheduler.py",
        "core/runtime_worker.py",
        "core/runtime_queue.py",
        "core/runtime_executor.py",
        "core/runtime_orchestrator.py",
        "core/runtime_dispatcher.py",
        "core/runtime_event_schema.py",
        "core/runtime_event_bus.py",
        "core/human_approval_gate.py",
        "core/human_approval_contract.py",
        "core/human_approval_store.py",
        "core/human_approval_audit.py",
        "core/approval_workflow.py",
        "core/kill_switch.py",
        "core/rollback_controller.py",
        "core/dry_run_executor.py",
        "core/tool_executor.py",
        "core/model_invoker.py",
        "core/context_builder.py",
        "core/output_delivery.py",
        "core/ui_tars_adapter.py",
        "core/hermes_adapter.py",
        "core/n8n_adapter.py",
        "core/home_assistant_adapter.py",
    ]:
        assert phrase in text
    for phrase in [
        "observability contract activo",
        "observability runtime",
        "audit trail operativo",
        "logger operativo",
        "event log operativo",
        "event bus operativo",
        "telemetry real",
        "metrics collector",
        "tracing real",
        "dashboard operativo",
        "immutable audit log operativo",
        "correlation ledger runtime",
        "side-effect ledger operativo",
        "redaction engine operativo",
        "log write real",
        "event publish real",
        "store write real",
        "store mutation real",
        "runtime state operativo",
        "runtime governance operativo",
        "runtime activation",
        "runtime execution",
        "runtime runner",
        "runtime scheduler",
        "runtime worker",
        "runtime queue",
        "runtime executor",
        "dry-run execution activation",
        "human approval operativo",
        "kill switch operativo",
        "rollback operativo",
        "tool execution",
        "model invocation",
        "context injection",
        "output delivery",
        "writes reales",
        "stores operativos",
        "memory persistence",
        "API calls",
        "network",
        "browser",
        "env access",
        "secret access",
        "UI-TARS runtime",
        "Hermes runtime",
        "n8n real workflows",
        "Home Assistant real actions",
        "Market Catalog runtime",
        "Business Composition Layer runtime",
        "OBLITERATUS integration",
    ]:
        assert phrase in text


def test_no_new_operational_observability_modules_were_created():
    forbidden_absent = [
        "core/observability_event.py",
        "core/observability_event_schema.py",
        "core/observability_snapshot.py",
        "core/observability_store.py",
        "core/observability_writer.py",
        "core/observability_reader.py",
        "core/observability_logger.py",
        "core/audit_trail.py",
        "core/audit_logger.py",
        "core/event_log.py",
        "core/event_bus.py",
        "core/telemetry.py",
        "core/metrics_collector.py",
        "core/tracing.py",
        "core/dashboard.py",
        "core/correlation_ledger.py",
        "core/immutable_audit_log.py",
        "core/side_effect_ledger.py",
        "core/redaction_engine.py",
    ]
    for path in forbidden_absent:
        assert not (ROOT / path).exists(), path
    observability_contract = ROOT / "core" / "observability_contract.py"
    assert observability_contract.exists()
    assert "Non-operational Observability contract" in observability_contract.read_text(encoding="utf-8")
    observability = ROOT / "core" / "observability.py"
    assert observability.exists()
    assert "Helpers no mutantes" in observability.read_text(encoding="utf-8")


def test_runtime_state_governance_activation_dry_run_and_kill_switch_flags_remain_false():
    flags = [
        state_contract.RUNTIME_STATE_OPERATIONAL,
        state_contract.RUNTIME_STATE_ACTIVATION_ENABLED,
        state_contract.RUNTIME_STATE_MUTATION_ENABLED,
        state_contract.RUNTIME_STATE_STORE_ENABLED,
        state_contract.RUNTIME_STATE_EVENT_BUS_ENABLED,
        state_contract.RUNTIME_STATE_RUNTIME_ACTIVATION_ENABLED,
        state_contract.RUNTIME_STATE_RUNTIME_EXECUTION_ENABLED,
        state_contract.RUNTIME_STATE_DRY_RUN_EXECUTION_ENABLED,
        state_contract.RUNTIME_STATE_TOOL_EXECUTION_ENABLED,
        state_contract.RUNTIME_STATE_MODEL_INVOCATION_ENABLED,
        state_contract.RUNTIME_STATE_CONTEXT_INJECTION_ENABLED,
        state_contract.RUNTIME_STATE_OUTPUT_DELIVERY_ENABLED,
        state_contract.RUNTIME_STATE_WRITES_ENABLED,
        state_contract.RUNTIME_STATE_STORES_ENABLED,
        state_contract.RUNTIME_STATE_NETWORK_ENABLED,
        state_contract.RUNTIME_STATE_SECRET_ACCESS_ENABLED,
        governance_contract.RUNTIME_GOVERNANCE_OPERATIONAL,
        governance_contract.RUNTIME_GOVERNANCE_ACTIVATION_ENABLED,
        governance_contract.RUNTIME_GOVERNANCE_EXECUTION_ENABLED,
        governance_contract.RUNTIME_GOVERNANCE_EVENT_BUS_ENABLED,
        governance_contract.RUNTIME_GOVERNANCE_AUDIT_RUNTIME_ENABLED,
        governance_contract.RUNTIME_GOVERNANCE_TOOL_EXECUTION_ENABLED,
        governance_contract.RUNTIME_GOVERNANCE_MODEL_INVOCATION_ENABLED,
        governance_contract.RUNTIME_GOVERNANCE_CONTEXT_INJECTION_ENABLED,
        governance_contract.RUNTIME_GOVERNANCE_OUTPUT_DELIVERY_ENABLED,
        governance_contract.RUNTIME_GOVERNANCE_WRITES_ENABLED,
        governance_contract.RUNTIME_GOVERNANCE_STORES_ENABLED,
        governance_contract.RUNTIME_GOVERNANCE_NETWORK_ENABLED,
        governance_contract.RUNTIME_GOVERNANCE_SECRET_ACCESS_ENABLED,
        RUNTIME_ACTIVATION_ENABLED,
        RUNTIME_EXECUTION_ENABLED,
        RUNTIME_RUNNER_ENABLED,
        RUNTIME_SCHEDULER_ENABLED,
        RUNTIME_WORKER_ENABLED,
        RUNTIME_QUEUE_ENABLED,
        RUNTIME_TOOL_EXECUTION_ENABLED,
        RUNTIME_MODEL_INVOCATION_ENABLED,
        RUNTIME_CONTEXT_INJECTION_ENABLED,
        RUNTIME_OUTPUT_DELIVERY_ENABLED,
        RUNTIME_WRITES_ENABLED,
        RUNTIME_STORES_ENABLED,
        RUNTIME_MEMORY_PERSISTENCE_ENABLED,
        RUNTIME_NETWORK_ENABLED,
        RUNTIME_API_ENABLED,
        RUNTIME_BROWSER_ENABLED,
        RUNTIME_FILESYSTEM_ENABLED,
        RUNTIME_ENV_ACCESS_ENABLED,
        RUNTIME_SECRET_ACCESS_ENABLED,
        RUNTIME_UI_TARS_ENABLED,
        RUNTIME_HERMES_ENABLED,
        RUNTIME_N8N_ENABLED,
        RUNTIME_HOME_ASSISTANT_ENABLED,
        dry_run_contract.DRY_RUN_EXECUTION_OPERATIONAL,
        dry_run_contract.DRY_RUN_EXECUTION_ENABLED,
        dry_run_contract.DRY_RUN_EXECUTOR_ENABLED,
        dry_run_contract.DRY_RUN_RUNNER_ENABLED,
        dry_run_contract.DRY_RUN_DISPATCHER_ENABLED,
        dry_run_contract.DRY_RUN_SCHEDULER_ENABLED,
        dry_run_contract.DRY_RUN_WORKER_ENABLED,
        dry_run_contract.DRY_RUN_QUEUE_ENABLED,
        dry_run_contract.DRY_RUN_TOOL_EXECUTION_ENABLED,
        dry_run_contract.DRY_RUN_MODEL_INVOCATION_ENABLED,
        dry_run_contract.DRY_RUN_CONTEXT_INJECTION_ENABLED,
        dry_run_contract.DRY_RUN_OUTPUT_DELIVERY_ENABLED,
        dry_run_contract.DRY_RUN_WRITES_ENABLED,
        dry_run_contract.DRY_RUN_STORES_ENABLED,
        dry_run_contract.DRY_RUN_NETWORK_ENABLED,
        dry_run_contract.DRY_RUN_SECRET_ACCESS_ENABLED,
        kill_switch_contract.KILL_SWITCH_ROLLBACK_OPERATIONAL,
        kill_switch_contract.KILL_SWITCH_ENABLED,
        kill_switch_contract.ROLLBACK_ENABLED,
        kill_switch_contract.KILL_SWITCH_EXECUTION_ENABLED,
        kill_switch_contract.ROLLBACK_EXECUTION_ENABLED,
        kill_switch_contract.PROCESS_TERMINATION_ENABLED,
        kill_switch_contract.JOB_CANCELLATION_ENABLED,
        kill_switch_contract.QUEUE_DRAIN_ENABLED,
        kill_switch_contract.WORKER_STOP_ENABLED,
        kill_switch_contract.SCHEDULER_STOP_ENABLED,
        kill_switch_contract.RUNNER_STOP_ENABLED,
        kill_switch_contract.EXECUTOR_STOP_ENABLED,
        kill_switch_contract.ROLLBACK_FILESYSTEM_ENABLED,
        kill_switch_contract.ROLLBACK_GIT_ENABLED,
        kill_switch_contract.ROLLBACK_STORE_MUTATION_ENABLED,
        kill_switch_contract.ROLLBACK_DATABASE_ENABLED,
        kill_switch_contract.ROLLBACK_MEMORY_ENABLED,
        kill_switch_contract.KILL_SWITCH_TOOL_EXECUTION_ENABLED,
        kill_switch_contract.KILL_SWITCH_MODEL_INVOCATION_ENABLED,
        kill_switch_contract.KILL_SWITCH_SECRET_ACCESS_ENABLED,
    ]
    assert flags == [False] * len(flags)


def test_obliteratus_is_excluded_as_observability_source():
    text = _text()
    for phrase in [
        "OBLITERATUS no forma parte de Observability Contract",
        "No es fuente observable",
        "No es fuente de eventos",
        "No es fuente de auditoria",
        "No es integracion",
        "No es dependency",
        "No es adapter",
        "No es provider",
        "No es capability",
        "No es runtime",
        "No es roadmap operativo",
        "No es governance source",
        "No es state source",
        "No es observability source",
    ]:
        assert phrase in text
